name: stevenwingate.com
favicon: null
layout_spectrum: 0.9844091115519404
typography_spectrum: 0.08553825039416552
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2958226704504341
  lightness: 0.6967778643593192
  saturation: 0.9768883048091084
  rhythmicContrast: 0.3909917580895126
purpose: []
